# Generated by Django 4.1.5 on 2023-02-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Adı')),
                ('text', models.TextField(max_length=700, verbose_name='Açıklama')),
                ('image', models.FileField(upload_to='', verbose_name='Fotograf')),
                ('fiyat', models.FloatField(default=0, verbose_name='Fiyat')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('star', models.FloatField(default=0, verbose_name='Beğeni')),
            ],
        ),
    ]
