# Generated by Django 4.1.5 on 2023-02-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urunler',
            new_name='Product',
        ),
    ]
