# Generated by Django 4.1.5 on 2023-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marka',
            field=models.CharField(max_length=50, null=True, verbose_name='Marka'),
        ),
    ]
